version: '3.8'

services:
  app :
   container_name: fitness-tracker
   working_dir: /app
   image: cosmtrek/air
   env_file:
     - .env
   volumes:
     - ./:/app
   ports:
     - 8080:8080
   command: sh -c "air"
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "15432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
