version: '3.8'

services:
  api :
   container_name: fitness-tracker
   working_dir: /app
   image: cosmtrek/air
   env_file:
     - api/.env
   volumes:
     - ./api:/app
   ports:
     - 8080:8080
   command: sh -c "air"
  db:
    image: postgres:alpine
    env_file:
      - api/.env.postgres
    ports:
      - "15432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
