### 

# @name get-all-exercises

GET https://fit-api.infiniter.tech/exercises HTTP/1.1
Authorization: Bearer {{accessToken}}


### 

# @name get-exercise-options

GET https://fit-api.infiniter.tech/exercises/options HTTP/1.1
Authorization: Bearer {{accessToken}}


### 

# @name create-exercise

POST https://fit-api.infiniter.tech/exercises HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "Benchpress"
}


### ======================================== ###


### 

# @name get-all-records

GET https://fit-api.infiniter.tech/records HTTP/1.1
Authorization: Bearer {{accessToken}}


### 

# @name create-record

POST https://fit-api.infiniter.tech/records HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "exerciseId": 1,
  "reps": [
    {
      "feeling": "easy",
      "weight": 100
    },
    {
      "feeling": "normal",
      "weight": 105
    },
    {
      "feeling": "hard",
      "weight": 110
    }
  ]
}


### 

# @name create-record-with-date

POST https://fit-api.infiniter.tech/records HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "date": "2024-01-15",
  "exerciseId": 1,
  "reps": [
    {
      "feeling": "easy",
      "weight": 100
    },
    {
      "feeling": "normal",
      "weight": 105
    }
  ]
}


### ======================================== ###


### 

# @name login

POST https://fit-api.infiniter.tech/login HTTP/1.1
Content-Type: application/json

{
  "name": "viktor",
  "pass": "mypassword"
}


### ======================================== ###


### 

# @name create-user

POST https://fit-api.infiniter.tech/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "viktor",
  "pass": "mypassword"
}


### ======================================== ###


### 

# @name create-async-job-for-exercises

POST https://fit-api.infiniter.tech/async-jobs HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "type": "fetch-exercises"
}


### 

# @name get-async-jobs

GET https://fit-api.infiniter.tech/async-jobs HTTP/1.1
Authorization: Bearer {{accessToken}}


### ======================================== ###


### 

# @name get-all-workouts

GET https://fit-api.infiniter.tech/workouts HTTP/1.1
Authorization: Bearer {{accessToken}}


### 

# @name get-workout-stats

GET https://fit-api.infiniter.tech/workouts/stats HTTP/1.1
Authorization: Bearer {{accessToken}}


### 

# @name get-workout-stats-by-date

GET https://fit-api.infiniter.tech/workouts/stats/2024-12-15 HTTP/1.1
Authorization: Bearer {{accessToken}}


### 

# @name get-workout-stats-by-date-today

GET https://fit-api.infiniter.tech/workouts/stats/2024-12-30 HTTP/1.1
Authorization: Bearer {{accessToken}}


### 

# @name create-workout

POST https://fit-api.infiniter.tech/workouts HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "label": "Push Day",
  "date": "2024-12-15"
}


### 

# @name create-workout-without-date

POST https://fit-api.infiniter.tech/workouts HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "label": "Leg Day"
}
